# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - "*"
  paths:
    include:
    - rootfs/*
    - Dockerfile
    - build.json
    - go.mod
    - main.go
    - http.go
    - supervisor.go
pr: none
variables:
  - name: versionBuilder
    value: "7.2.0"
  - group: docker
  - group: github
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:

  - stage: "Build"
    jobs:
      - job: "ReleaseDocker"
        timeoutInMinutes: 240
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          maxParallel: 5
          matrix:
            amd64:
              buildArch: "amd64"
            i386:
              buildArch: "i386"
            armhf:
              buildArch: "armhf"
            armv7:
              buildArch: "armv7"
            aarch64:
              buildArch: "aarch64"
        steps:
          - template: templates/azp-step-plugin-version.yaml@azure
          - template: templates/azp-step-build-generic.yaml@azure
            parameters:
              buildArch: $(buildArch)
              buildVersion: $(pluginRelease)

  - stage: "Publish"
    jobs:
      - job: "ReleaseHassio"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: templates/azp-step-plugin-version.yaml@azure
          - template: templates/azp-step-version-push.yaml@azure
            parameters:
              jsonTag: observer
              commitName: Observer
              buildVersion: $(pluginRelease)
